apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargo-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp
  project: default
  source:
    repoURL: https://github.com/UnpredictablePrashant/ArgoCD.git
    targetRevision: HEAD
    path: k8s/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
